/********    PART I     *********/      
---------   QUERY #2    ---------  


/***    FIND THE NUMBER OF ORDERS THAT EACH USER HAS MADE IN EVERY CITY AND PUT THEM IN DESCENDING ORDER    ***/ 
WITH CITY_USERS_ORDERED  AS(
  SELECT
    CITY
    ,USER_ID 
    ,COUNT(ORDER_ID) ORDERS
    ,ROW_NUMBER() OVER(PARTITION BY CITY ORDER BY COUNT(ORDER_ID) DESC) RN
  FROM 
    `efood2022-376017.main_assessment.orders` 
  GROUP BY 
    CITY,USER_ID 
)


/***    KEEP THE TOP 10 USERS WITH THE MOST ORDERS FOR EACH CITY    ***/
,TOP10_CITY_USERS AS(
  SELECT
    CITY
    ,SUM(ORDERS) ORDERS_OF_TOP10_USERS
  FROM
    CITY_USERS_ORDERED
  WHERE RN <= 10
  GROUP BY CITY
)


/***    CALCULATE THE PERCENTAGE OF TOP 10 USERS OF EACH CITY CONTRIBUTE TO THEIR CITY    ***/
SELECT
  A.CITY
  ,ROUND(B.ORDERS_OF_TOP10_USERS / COUNT(ORDER_ID) * 100,2)   AS TOP10_PERC
FROM
  `efood2022-376017.main_assessment.orders` A
  INNER JOIN TOP10_CITY_USERS B ON A.CITY = B.CITY
GROUP BY A.CITY,B.ORDERS_OF_TOP10_USERS
